services:
  pve-vm-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      # Without terminating /
      - PM_HOST=https://10.0.1.10:8006/api2/json 
      - PM_NODE=hv
      - PM_WEBSERVER_PORT=8080 # see proxmox_fileserver/

      # Expected in env file
      - PM_API_USER=${api_user}
      - PM_API_KEY=${api_key}