services:
  http-fileserver:
    image: halverneus/static-file-server:latest
    restart: unless-stopped
    volumes:
      - '/opt/images:/web'
    ports:
      - "8080:8080"
    user: "${id_user}:${id_group}"
    # Run bootstrap.sh first