name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'proxmox_fileserver/**'
    - '**/docker-compose.yaml'
    - '**/*.md'
    - '**/.*ignore'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
    - '**/docker-compose.yaml'
    - '**/*.md'
    - '**/.*ignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . -t ${{ github.event.repository.name }}:$(date +%s)
